### ISSUE TITLE
why i am getting this error File "migrations\env.py", line 25, in <module>     str(current_app.extensions['migrate'].db.get_engine().url).replace( AttributeError: 'MySQL' object has no attribute 'get_engine'

### ISSUE THREAD

**Issue by Josaphat12-tech** [Vaibhavi24/Online-Hotel-Management-System#26]
![luc](https://user-images.githubusercontent.com/85907186/124382074-3544b100-dcce-11eb-8da8-b36f849a803e.jpg)

guys i need help i am using this sample project but am getting issue while runnin' my app...
've create the msqldb but it still can't work.

**Comment by contactvaibhavi** [comment]
Fixed, pls try now
